config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :products
  # Defines the root path route ("/")
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories

  validates :name, presence: true
  validates :price, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    # TODO: Order by, list of all products with the same category
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: 'El producto se guardó exitosamente.'
    else
      flash[:product_errors] = @product.errors.full_messages
      redirect_back fallback_location: 'products/new'
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, notice: 'El producto se actualizó exitosamente.'
    else
      render :edit
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.categories.clear
    product.destroy

    redirect_to products_path, notice: 'El producto fue eliminado exitosamente.'
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def form_title
    @product.new_record? ? 'Publicar producto' : 'Modificar producto'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Productos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-1">
      <h2><%= form_title %></h2>

      <%= form_for @product do |form| %>
        <div class="form-group">
          <%= form.text_field :name, class: "form-control input-lg", placeholder:
          "Ingresa el nombre del producto", autocomplete: "off" %>
        </div>

        <div class="form-group">
          <%= form.number_field :price, class: "form-control input-lg",
          placeholder: "Ingresa el valor del producto", autocomplete: "off",  pattern: "^\d*(\.\d{0,2})?$"%>
        </div>

        <div class="form-group">
          <%= hidden_field_tag "product[category_ids][]", nil %>
          <% Category.all.each do |category| %>
            <div class="form-check">
              <%= check_box_tag "product[category_ids][]", category.id, @product.category_ids.include?(category.id), id: dom_id(category) %>
              <%= category.name %>
            </div>
          <% end %>
        </div>

        <div>
          <%= form.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if flash[:product_errors] %>
<ul>
  <% flash[:product_errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Lista de productos</h1>
      <div class="text-right">
        <%= link_to "Crear", new_product_path, class: "btn btn-primary" %>
      </div>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Precio</th>
            <th scope="col">Categorías</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
          <tr>
            <td><%= link_to product.name, product %></td>
            <td>$<%= product.price %></td>
            <td><%= product.categories.map(&:name).join(', ') %></td>
            <td>
              <%= link_to edit_product_path(product), class: "btn btn-warning" do  %>
                <i class="fa-solid fa-pen-to-square fs-10"></i>
              <% end %>
              <%= link_to product, method: :delete, class: "btn btn-danger", data: { confirm: "¿De verdad quieres borrar este producto?"} do  %>
                <i class="fa-solid fa-trash fs-10"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @product.name %></h1>
      <p>Precio: $<%= @product.price %></p>
    </div>
  </div>
</div>